# Generated by Django 5.0.2 on 2025-03-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
