# Generated by Django 5.0.2 on 2025-03-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_about_nationality_about_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.AddField(
            model_name='skill',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
