# Generated by Django 5.0.2 on 2025-03-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_skill_icon_skill_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='work_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
