# Generated by Django 5.0.2 on 2025-03-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_experience_date_experience_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='academy_name',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='degree',
            new_name='level_of_education',
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_of_completion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
