# Generated by Django 5.0.2 on 2025-03-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_academy_name_education_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='starting_date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_of_completion',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
