# Generated by Django 5.0.2 on 2025-03-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_education_starting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
