# Generated by Django 5.0.2 on 2025-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_about_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
